spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        default_schema: auth
    open-in-view: false
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/qrcheck
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 10
      idle-timeout: 200000
      minimum-idle: 2
      schema: auth
  liquibase:
    enabled: false
  groovy:
    template:
      check-template-location: false
  security:
    api-key:
      name: X-ApiKey-Authorization
      token:
        incoming:
          - 89414993-6e9f-45e6-a0ec-9eb5b7cbb2fe #user-handler
          - fc28c7e5-fb14-4335-9aa1-e0921cfdd4b9 #google-auth
        outgoing: d88d2dab-4002-4d7c-b259-d9682df4f22b

outbound:
  feign:
    google-auth:
      host: "http://localhost:${OUTBOUND_FEIGN_GOOGLE_AUTH_PORT}/oauth2"
    user-handler:
      host: "http://localhost:${OUTBOUND_FEIGN_USER_HANDLER_PORT}/inner"

logbook:
  strategy: body-only-if-status-at-least
  format:
    style: http
  logger:
    name: AUTH-HANDLER-REST
  exclude:
    - /actuator/**