spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
        default_schema: auth
    open-in-view: false
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/qrcheck
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/qrcheck
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      pool-name: HikariPool
      max-lifetime: 600000
      connection-timeout: 15000
      maximum-pool-size: 10
      idle-timeout: 200000
      minimum-idle: 2
      schema: ${spring.jpa.properties.hibernate.default_schema}
  liquibase:
    enabled: false
  sleuth:
    jdbc:
      p6spy:
        enabled: true
        enable-logging: true
        tracing:
          include-parameter-values: true
  groovy:
    template:
      check-template-location: false

springdoc:
  api-docs:
    path: "/swagger-api"
    enabled: true
  swagger-ui:
    path: "/"
  info:
    title: Auth Handler RESTful API
    description: Сервис управления аутентификцией
    version: V1
    licence-url: https://qrchk.ru/licence
    owner-name: QRCheck
    owner-url: https://qrchk.ru
    owner-email: it.support@softdarom.ru

outbound:
  feign:
    google-auth:
      host: ${GOOGLE_AUTH_URL}
    user-handler:
      host: ${USER_HANDLER_URL}

logbook:
  strategy: body-only-if-status-at-least
  format:
    style: http
  logger:
    name: REST
  exclude:
    - /actuator/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - /swagger-api/**