---
work_dir: "/opt/auth-handler"

application:
  name: auth-handler
  port:
    tcp:
      name: tcp
      number: 8000
    actuator:
      name: actuator
      number: 7000

  path:
    config: "{{ work_dir }}/config"
    logs: "{{ work_dir }}/logs"

docker:
  project: qrcheck
  image: auth-handler